Creating product POST
software-riders/food-commander-be pull request #2
Opened 2023-04-11 19:26 UTC by ThiagoSousaSantana

#1

2023-04-11 19:50 UTC, welbertFC commented on src/main/kotlin/br/com/foodcommander/controller/ProductController.kt
> +    fun postProduct(@RequestBody productRequest: ProductRequest): ResponseEntity<Product> {
Utilizar um objeto Response para retorno e não utilizar o entity

2023-04-11 19:50 UTC, welbertFC commented on src/main/kotlin/br/com/foodcommander/controller/ProductController.kt
> +                Product(null, productRequest.name, productRequest.description))
ao invés de passar null na instanciação do objeto pode no model atribuir null ao valor, assim não precisando passar o null na criação do objeto

2023-04-11 19:50 UTC, welbertFC commented on src/main/kotlin/br/com/foodcommander/controller/dto/ProductRequest.kt
> +data class ProductRequest(
não agora mas adicionar validações, notblank por exemplo

2023-04-11 19:50 UTC, welbertFC commented on src/main/kotlin/br/com/foodcommander/controller/ProductController.kt
> +                Product(null, productRequest.name, productRequest.description))
utilizar um converter ao ivés de instanciar o objeto

2023-04-11 19:50 UTC, welbertFC commented on src/main/kotlin/br/com/foodcommander/models/Product.kt
> +        val id: String?,
pode atribuir null a variavel para evitar ter que passar null ao criar este objeto

2023-04-11 19:50 UTC, welbertFC commented on src/main/kotlin/br/com/foodcommander/service/ProductService.kt
> +class ProductService(val repository: ProductRepository) {
funções com uma ação podem ser escritas em uma unica linha por exemplo :

 fun createProduct(product: Product) =  repository.insert(product)

2023-04-11 20:13 UTC, NewtonCesarRoncari commented on src/main/kotlin/br/com/foodcommander/controller/ProductController.kt
> +                Product(null, productRequest.name, productRequest.description))
utilizar Named Parameter

```suggestion
                Product(name = productRequest.name, description = productRequest.description))
```

2023-04-11 20:17 UTC, NewtonCesarRoncari commented on src/main/kotlin/br/com/foodcommander/service/ProductService.kt
> +class ProductService(val repository: ProductRepository) {
Acredito que explicitar o retorno do método protege o escopo de ser alterado futuramente e acabar mudando o retorno, más é discutível

2023-04-11 20:21 UTC, NewtonCesarRoncari commented on src/main/kotlin/br/com/foodcommander/controller/ProductController.kt
> +@RequestMapping("/v1/products")
só dúvida mesmo, "v1" tem que ficar na classe ?, não deveria ser uma constante em uma URL base ?

2023-04-12 23:20 UTC, welbertFC approved these changes

2023-04-13 01:49 UTC, NewtonCesarRoncari requested changes

2023-04-13 01:49 UTC, NewtonCesarRoncari commented on src/main/kotlin/br/com/foodcommander/controller/ProductController.kt
> +                    urlPicture = productRequest.urlPicture ?: "",
Que tal ?
```suggestion
                    urlPicture = productRequest.urlPicture.orEmpty(),
```

2023-04-13 01:49 UTC, NewtonCesarRoncari commented on src/main/kotlin/br/com/foodcommander/controller/ProductController.kt
> +                    id = product.id!!,
!! é arriscado, considerado um antipattern, sugiro uma verificação

2023-04-13 22:37 UTC, ThiagoSousaSantana commented on src/main/kotlin/br/com/foodcommander/controller/ProductController.kt
> +                    id = product.id!!,
é uma solução temporaria, vamos implementar um mapper

2023-04-13 22:38 UTC, merged